evn: "local"
database:
  storage_url: "postgres://postgres:1234@localhost:5436/taskmanag?sslmode=disable"
  migrations_path: "migrations"
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
  user: "supreme"
  password: "1234"

